version: 1.0.0-{build}
image:
  - Visual Studio 2019
environment:
  PYTHON: "C:\\Python38"
  PATH: "%PYTHON%;%PATH%"

before_build:
  - cmd: pip install -r requirements.txt

build_script:
  - cmd: python -m pytest test.py
