install:
- py -m venv env
- env/Scripts/activate
- pip install flask
- pip install pillow
- pip install numpy
- pip install matplotlib
- pip install -U Flask-WTF
- pip install wtforms
- py ./projectweb/app.py
- name: Start tests
 run: pipenv run python -m pytest app.py
