version: 1.0.{build}
image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - 'SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%'
  - pip install --upgrade pip
  - pip install -r requirements.txt

build_script:
  - python setup.py build

test_script:
  - python setup.py test
